[package]
name = "game101_5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.15.0"
rand = "0.8.4"
image = "0.23.14"
obj-rs = "0.6.3"
